### ISSUE TITLE
Take advantage of Elixir's tail-call optimization

### ISSUE THREAD

**Issue by stevegrossi** [stevegrossi/fibonacci#2]

**Comment by janxious** [comment]
This is an example of using the TCO feature: https://github.com/stevegrossi/fibonacci/pull/1/commits/367ad91dbd14995f75d2018c8cbea74f3a9e0165

**Comment by stevegrossi** [comment]
Indeed, and this ended up becoming a non-issue with the switch to using `Stream.unfold/2` from Elixir's standard library.
