### ISSUE TITLE
Eliminate redundancy when calculating numbers in the series

### ISSUE THREAD

**Issue by stevegrossi** [stevegrossi/fibonacci#3]
Currently, this library calculates each number each numbed three times. For example, when generating `3` in the series `[5, 3, 2, 1, 1, 0]`, we first generate `2` and `1`. Then, when generating `5` we generate `3` and `2` again! How can we avoid this?

**Comment by janxious** [comment]
#1 results in only ever calculating any given number once.

**Comment by stevegrossi** [comment]
Indeed, and this ended up becoming a non-issue with the switch to using `Stream.unfold/2` from Elixir's standard library.
